
services:
  db:
    image: postgres:latest
    container_name: mydb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2157
      POSTGRES_DB: aiwebapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    image: my-ai-list:latest
    container_name: myapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/aiwebapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2157
    depends_on:
      - db

volumes:
  postgres_data: